Myw8ForAesthetics/clienti/urls.py
from django.urls import path
from .views import sceltamenu, sceltacliente, sceltapostcliente, sceltamisure
from .views import get_codice_fiscale, search_clienti
from .views import crea_cliente, crea_cliente_piva, crea_cliente_minore
from .views import info_cliente, modifica_cliente
from .views import crea_misura, riepilogo_misura, inviopcu, riepilogo_misura_elenco

app_name = 'clienti'

urlpatterns = [
    # Altre URL dell'applicazione...
    path('', sceltamenu, name='sceltamenu'),
    path('tipo', sceltacliente, name='tipocliente'),
    path('post', sceltapostcliente, name='postcliente'),
    path('misure',  sceltamisure, name='scelta_misure'),

    path('nuovo', crea_cliente, name='nuovocliente'),
    path('nuovopiva', crea_cliente_piva, name='nuovoclientepiva'),
    path('nuovominore', crea_cliente_minore, name='nuovoclienteminore'),

    path('nuovamisura', crea_misura, name='nuovamisura'),
    path('misurariepilogo/<int:id>/', riepilogo_misura,
         name='misure_riepilogo_clienti'),
    path('misurariepilogocliente/<int:id>/', riepilogo_misura_elenco,
         name='misure_riepilogo_clienti_elenco'),
    path('inviopcu/<int:id>/', inviopcu, name='inviopcu'),



    path('search/', search_clienti, name='search_clienti'),

    path('informazioni/<int:id>/', info_cliente, name='info_cliente'),
    path('modifica/<int:id>/', modifica_cliente, name='modifica_cliente'),

    path('ajax/cf', get_codice_fiscale, name='ajax_codice_fiscale'),


]

Myw8ForAesthetics/ordini/urls.py
from django.urls import path
from .views import sceltagruppo, sceltalistino, sceltapagamento, riassuntoinfo
from .views import misure_mancanti, modulodati_mancante, moduloalimenti_mancante, invio_moduli
from .views import invio_ordine, elenco_ordini
from .views import info_ordine

app_name = 'ordini'

urlpatterns = [

    path('sceltaprogramma/<int:id>/',  sceltagruppo, name='scelta_gruppo'),
    path('sceltapagamento/<int:id>/',  sceltapagamento, name='scelta_pagamento'),
    path('sceltalistino/<int:id>/<int:pg>',
         sceltalistino, name='scelta_listino'),
    path('riassuntoprogramma/<int:id>/',
         riassuntoinfo, name='riassunto_programma'),
    path('sceltalistino/',  misure_mancanti, name='misura_mancante'),
    path('invioordine/<int:id>',  invio_ordine, name='invio_ordine_mail'),
    path('inviomoduli/<int:id>',  invio_moduli, name='invio_moduli_mail'),
    path('inserimentodati/<int:id>',  modulodati_mancante, name='modulodati_mancante'),
    path('inserimentoalimenti/<int:id>',  moduloalimenti_mancante, name='moduloalimenti_mancante'),
    path('lista_ordini/',  elenco_ordini, name='lista_ordini'),
    path('infoordine/<int:id>',  info_ordine, name='info_ordine'),
]

Myw8ForAesthetics/clienti/models.py
from django.db import models
from consulenti.models import AnagraficaConsulente
from accordi.models import Programmi
from amministrazione.models import Alimenti
from multiselectfield import MultiSelectField

# Create your models here.
class AnagraficaCliente(models.Model):

    Sesso = (

        ('M', 'M'),
        ('F', 'F')
        )

    nome = models.CharField(max_length=50)
    cognome = models.CharField(max_length=50)
    citta_nascita = models.CharField(max_length=25)
    data_nascita = models.DateField()
    indirizzo = models.CharField(max_length=100)
    numero_civico= models.CharField(max_length=10, null=True)
    cap = models.CharField(max_length=5)
    citta = models.CharField(max_length=25)
    codice_fiscale = models.CharField(max_length=16)
    telefono = models.CharField(max_length=15,blank=True,null=True)
    cellulare = models.CharField(max_length=15)
    altezza = models.CharField(max_length=7, blank=True,null=True)
    email = models.EmailField(max_length=150)
    sesso = models.CharField(max_length=1, choices=Sesso)
    note = models.TextField(blank=True,null=True)
    privacy = models.BooleanField(default=False)

    """ Consulente """
    consulente = models.ForeignKey(AnagraficaConsulente, on_delete=models.SET_NULL,null=True)

    """ Date modifica """
    data_creazione = models.DateTimeField(auto_now_add=True)
    data_ultima_modifica = models.DateTimeField(auto_now_add=True)


    """ Dati Anagrafici Persona Giuridica"""
    ragione_sociale = models.CharField(max_length=100,null=True,blank=True)
    sede = models.CharField(max_length=50,blank=True,null=True, default="")
    indirizzo_sede = models.CharField(max_length=100,null=True,blank=True,default="")
    cap_sede= models.CharField(max_length=5,null=True,blank=True,default="")
    telefono_sede = models.CharField(max_length=15,null=True,blank=True,default="")
    email_sede = models.EmailField(max_length=100,null=True,blank=True,default="")
    partita_iva = models.CharField(max_length=11,null=True,blank=True)
    codice_univoco = models.CharField(max_length=8,null=True,blank=True)

    """Dati Anagrafici Beneficiario"""
    beneficiario_nome = models.CharField(max_length=50,null=True,blank=True)
    beneficiario_cognome = models.CharField(max_length=50,null=True,blank=True)
    beneficiario_cellulare = models.CharField(max_length=15,null=True,blank=True)
    beneficiario_codice_fiscale = models.CharField(max_length=16,null=True,blank=True)


    def __str__(self):

        return self.nome + " " + self.cognome


    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clienti"


class PatologieClienti(models.Model):

    COLPITI = (
            ('T', 'Tutti'),
            ('U', 'Uomo'),
            ('D', 'Donna')
            )

    nome = models.CharField(max_length=50)
    patologia_sesso = models.CharField(max_length=1,choices=COLPITI, default=0)

    def __str__(self):

        return self.nome

class PersonalCheckUpCliente(models.Model):


    cliente = models.ForeignKey(AnagraficaCliente, on_delete=models.CASCADE)
    data = models.DateField(auto_now_add=True)
    peso = models.FloatField(verbose_name="Peso")
    bmi = models.FloatField(verbose_name="Bmi")
    grasso_corporeo = models.FloatField(null=True,blank=True, verbose_name="Grasso corporeo")
    muscolatura = models.FloatField(null=True,blank=True, verbose_name="Muscolatura")
    metabolismo = models.FloatField(null=True,blank=True, verbose_name="Metabolismo")
    grasso_viscerale = models.FloatField(null=True,blank=True, verbose_name="Grasso viscerale")
    collocm = models.FloatField(verbose_name="Centimetri collo")
    toracecm = models.FloatField(verbose_name="Centimetri torace")
    cosciadxcm = models.FloatField(verbose_name="Centimetri coscia destra")
    cosciasxcm = models.FloatField(verbose_name="Centimetri coscia sinistra")
    fianchicm = models.FloatField(verbose_name="Centimetri fianchi")
    addomecm = models.FloatField(verbose_name="Centimetri addome")
    ginocchiodxcm = models.FloatField(verbose_name="Centimetri ginocchio destro")
    ginocchiasxcm = models.FloatField(verbose_name="Centimetri ginocchio sinistro")
    peso_ottimale = models.CharField(max_length= 6, null=True,blank=True)
    peso_desiderato =  models.CharField(max_length= 6,null=True,blank=True)
    programma = models.ForeignKey(to= 'accordi.Programmi', on_delete=models.CASCADE, blank=True, null=True)



    def __str__(self):

        return self.cliente.cognome + ' ' +str(self.peso)

class AnagraficaClienteDati(models.Model):

    SCELTA = (

        (1, 'Si'),
        (0, 'No')
        )

    SCELTA3 = (

        (0, 'No'),
        (1, 'Si'),
        (2,'A volte')
        )

    CIVILE = (
        ('Libero', 'Libero'),
        ('Coniugato', 'Coniugato')
        )

    FISICO = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E')
        )

    SCELTADIABETE= (

        ( 'Tipo 1', 'Tipo 1'),
        ( 'Tipo 2', 'Tipo 2')
        )

    MESIGRAVIDANZA =(
        ( '0', '0'),
        ( '1', '1'),
        ( '2', '2'),
        ( '3', '3'),
        ( '4', '4'),
        ( '5', '5'),
        ( '6', '6'),
        ( '7', '7'),
        ( '8', '8'),
        ( '9', '9')

    )

    GIORNI =(
        ( '0', '0'),
        ( '1', '1'),
        ( '2', '2'),
        ( '3', '3'),
        ( '4', '4'),
        ( '5', '5'),
        ( '6', '6'),
        ( '7', '7')
    )

    GRUPPO =(
        ('N', 'Non so'),
        ( '0', '0'),
        ( 'A', 'A'),
        ( 'B', 'B'),
        ( 'AB', 'AB')
    )

    ALIMENTAZIONE =(
        ( 'Onnivoro', 'Onnivoro'),
        ( 'Vegetariano', 'Vegetariano'),
        ( 'Vegano', 'Vegano')
    )
    PRESSIONE =(
        ( 'Normale', 'Normale'),
        ( 'Ipoteso', 'Ipoteso'),
        ( 'Iperteso', 'Iperteso')
    )
    ALIMENTI =(
        ( 'Caffè', 'Caffè'),
        ( 'Pane', 'Pane'),
        ( 'Verdure', 'Verdure'),
        ( 'Carne', 'Carne'),
        ( 'Cereali', 'Cereali'),
        ( 'Cioccolata', 'Cioccolata'),
        ( 'Legumi', 'Legumi'),
        ( 'Alcolici', 'Alcolici'),
        ( 'Pasta', 'Pasta'),
        ( 'Frutta', 'Frutta'),
        ( 'Pesce', 'Pesce'),
        ( 'Dolci', 'Dolci'),
        ( 'Pizza', 'Pizza'),
        ( 'Latticini', 'Latticini')
    )

    SAPORI =(
        ( 'Piccante', 'Piccante'),
        ( 'Dolce', 'Dolce'),
        ( 'Salato', 'Salato'),
        ( 'Amaro', 'Amaro'),
        ( 'Aspro', 'Aspro'),
        ( 'Insipido', 'Insipido')
    )

    CAR1 = (

        (1, 'Individualista'),
        (0, 'Altruista')
        )

    CAR2 = (

        (1, 'Estroverso'),
        (0, 'Introverso')
        )

    CAR3 = (

        (1, 'Ottimista'),
        (0, 'Pessimista')
        )

    SFOGO =(
            ('Dentro', 'Dentro'),
            ('Fuori', 'Fuori'),
            ('Non so','Non so')
            )

    GIORNATA  =(
            ('Mattina', 'Mattina'),
            ('Pomeriggio', 'Pomeriggio'),
            ('Sera','Sera')
            )

    DETERMINATO =(
        ( 0, '0'),
        ( 1, '1'),
        ( 2, '2'),
        ( 3, '3'),
        ( 4, '4'),
        ( 5, '5'),
        ( 6, '6'),
        ( 7, '7'),
        ( 8, '8'),
        ( 9, '9'),
        (10,'10')
        )

    PASTI = (
        (1, 'Sempre'),
        (2, 'Colazione'),
        (3, 'Pranzo'),
        (4, 'Cena'),
        (5, 'Mai')

    )

    cliente= models.OneToOneField(AnagraficaCliente,related_name='cliente',on_delete=models.CASCADE)
    provincia_nascita = models.CharField(max_length=50)
    stato_nascita = models.CharField(max_length=50)
    provincia = models.CharField(max_length=50)
    stato =  models.CharField(max_length=50)
    professione = models.CharField(max_length=50)
    stato_civile = models.CharField(max_length=15, choices=CIVILE, default='Libero')
    maggiorenne = models.BooleanField(choices=SCELTA, default=1)
    peso_attuale = models.CharField(max_length=5)
    altezza = models.CharField(max_length=5)
    bmi = models.CharField(max_length=8)
    stato_attuale = models.CharField(max_length=20)
    peso_ottimale = models.CharField(max_length=5)
    scostamento_peso = models.CharField(max_length=7)
    peso_desiderato = models.CharField(max_length=5)
    struttura_fisica = models.CharField(max_length=1, choices=FISICO, default='A')
    struttura_desiderata = models.CharField(max_length=1, choices=FISICO, default='A')
    pressione_arteriosa = models.CharField(max_length=10, choices=PRESSIONE, default='Normale')
    diabete = models.BooleanField(choices=SCELTA, default=0)
    tipo_diabete =  models.CharField(max_length=10,choices=SCELTADIABETE, null= True,blank=True)
    menopausa =  models.BooleanField(choices=SCELTA, default=0)
    gravidanza =  models.BooleanField(choices=SCELTA, default=0)
    mesi_gravidanza = models.CharField(max_length=1,choices=MESIGRAVIDANZA,null= True,blank=True)
    rapporto_corpo = models.IntegerField(choices=SCELTA3, default=0)
    droghe = models.BooleanField(choices=SCELTA, default=0)
    allergie = models.BooleanField(choices=SCELTA, default=0)
    allergie_elenco = models.CharField(max_length=100,null= True,blank=True)
    farmaci = models.BooleanField(choices=SCELTA, default=0)
    farmaci_elenco = models.CharField(max_length=100,null= True,blank=True)
    sport = models.BooleanField(choices=SCELTA, default=0)
    sport_praticato =  models.CharField(max_length=30,null= True,blank=True)
    sport_praticato_giorni = models.CharField(max_length=1,choices=GIORNI, null= True,blank=True)
    gruppo_sanguigno = models.CharField(max_length=7,choices=GRUPPO, default='N')
    insonnia = models.IntegerField(choices=SCELTA3, default=0)
    stitichezza = models.IntegerField(choices=SCELTA3, default=0)
    fumo = models.BooleanField(choices=SCELTA, default=0)
    numero_sigarette =  models.CharField(max_length=3, null= True,blank=True)
    delta_numero_sigarette = models.CharField(max_length=3, null= True,blank=True)

Myw8ForAesthetics/clienti/templates/clienti/elencoclienti.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Elenco Clienti {% endblock title %}
{% block header %}

<div id="text_header_rect" class = 'purple_rect'>
    <p id="text_header" class="text"> Elenco Clienti </p>
</div>

{% endblock header%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/clientesearch.css' %}" />
{% endblock css %}
{% block scriptlibrerie %}
 
{% endblock scriptlibrerie %}
{% block content %}
   
<div class="elenco-container">
    
    <form method="get" novalidate>
        <div id= 'form_cerca'>
            <div class="form-floating">
                
                {% render_field form.search_query class="form-control" %}
                <label class="font-custom" for="{{ form.search_query.id_for_label }}">{{ form.search_query.label_tag }}</label>

            </div>
            <button id= 'button_crea' class="bottone_viola" type="submit"><p id = 'menu_text_button'> Cerca </p></button>
        </div>
        
  
        
    </form>
    <div class =' table_conteiner'>   
        <table class = "tabella_cliente">
           
            {% for elemento in page_obj %}
                <tr>
                    {% if elemento.beneficiario_cognome %}
                        <td class="text-center col-auto iconae" >
                            <img class='ics' src="{% static 'static_file/minore.png'%}"> 
                        </td> 
                    {% elif elemento.ragione_sociale %}
                        <td class="text-center col-auto iconae">
                            <img class='ics' src="{% static 'static_file/iva.png'%}" > 
                        </td>
                    {% else %}
                        <td class="text-center col-auto iconae" >
                            {% if elemento.sesso == 'M' %}
                                <img class='ics' src="{% static 'static_file/man.png'%}">
                            {% else %}
                                <img class='ics' src="{% static 'static_file/woman.png'%}">
                            {% endif %}    
                        </td>
                    {% endif %}
                    <td><p id = 'table_text_button'> {{ elemento.nome }}</p></td>
                    <td><p id = 'table_text_button'>{{ elemento.cognome }}</p></td>
                    <td>
                        <div class="button_conteiner">
                            <a href="{% url 'clienti:info_cliente' elemento.id %}" id= 'button_info' class="bottone_clienti"><p id = 'cliente_text_button'> Informazioni </p></a>
                            <a href="{% url 'ordini:scelta_gruppo' elemento.id %}" id= 'button_info' class="bottone_clienti"><p id = 'cliente_text_button'> Accordo </p></a>
                            <a href="{% url 'clienti:misure_riepilogo_clienti_elenco' elemento.id %}" id= 'button_info' class="bottone_clienti"><p id = 'cliente_text_button'> bmi </p></a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        
        <div class="pagination">
            <span class="step-links left">
                {% if page_obj.has_previous %}               
                    <!--  <a href="?page=1">&laquo; prima</a> -->
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <img src={% static '/static_file/freccia_sinistra.png' %} alt="Icona" width="60px" height="20px">
                    </a>
                {% else %}
                    <a href="" style='visibility: hidden'>Precedente</a>
                {% endif %}
            </span>
            
            <span class="step-links center">
                <span class="current-page">
                    Pagina {{ page_obj.number }} di {{ page_obj.paginator.num_pages }}.
                </span>
            </span>
            
            <span class="step-links right">
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">
                        <img src={% static '/static_file/freccia_destra.png' %} alt="Icona" width="60px" height="20px">
                    </a>
                    <!--<a href="?page={{ page_obj.paginator.num_pages }}">ultima &raquo;</a> -->
                {% else %}
                <a href="" style='visibility: hidden'>Successiva</a>
                {% endif %}
            </span>
        </div>

    </div>
</div>

{% endblock %}
{% block script %}


  
{% endblock script %}

Myw8ForAesthetics/clienti/templates/clienti/modificacliente.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Nuovo Clienti {% endblock title %}
{% block header %}
<div id="text_header_rect" class = 'purple_rect'>
    <p id="text_header" class="text"> Modifica Cliente Privato </p>
</div> 

{% endblock header%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/formgrid.css' %}" />
{% endblock css %}
{% block scriptlibrerie %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
{% endblock scriptlibrerie %}

{% block content %}
   
<div class="form-container">
  <form  method="post" novalidate>{% csrf_token %}
    <div class="grid-form">

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.nome.errors %}
            {% render_field form.nome class="form-control is-invalid" %}
            {% for error in form.nome.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.nome class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.nome class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.nome.id_for_label }}">{{ form.nome.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.cognome.errors %}
            {% render_field form.cognome class="form-control is-invalid" %}
            {% for error in form.cognome.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.cognome class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.cognome class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.cognome.id_for_label }}">{{ form.cognome.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.citta_nascita.errors %}
            {% render_field form.citta_nascita class="form-control is-invalid" %}
            {% for error in form.citta_nascita.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.citta_nascita class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.citta_nascita class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.citta_nascita.id_for_label }}">{{ form.citta_nascita.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.data_nascita.errors %}
            {% render_field form.data_nascita class="form-control is-invalid" %}
            {% for error in form.data_nascita.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.data_nascita class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.data_nascita class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.data_nascita.id_for_label }}">{{ form.data_nascita.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.sesso.errors %}
            {% render_field form.sesso class="form-control is-invalid" %}
            {% for error in form.sesso.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.sesso class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.sesso class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.sesso.id_for_label }}">{{ form.sesso.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.codice_fiscale.errors %}
            {% render_field form.codice_fiscale class="form-control is-invalid" %}
            {% for error in form.codice_fiscale.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.codice_fiscale class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.codice_fiscale class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.codice_fiscale.id_for_label }}">{{ form.codice_fiscale.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.indirizzo.errors %}
            {% render_field form.indirizzo class="form-control is-invalid" %}
            {% for error in form.indirizzo.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.indirizzo class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.indirizzo class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.indirizzo.id_for_label }}">{{ form.indirizzo.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.cap.errors %}
            {% render_field form.cap class="form-control is-invalid" %}
            {% for error in form.cap.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.cap class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.cap class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.cap.id_for_label }}">{{ form.cap.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.citta.errors %}
            {% render_field form.citta class="form-control is-invalid" %}
            {% for error in form.citta.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.citta class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.citta class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.citta.id_for_label }}">{{ form.citta.label_tag }}</label>
      </div>   

      <div class="form-floating mb-3">
      
            {% render_field form.telefono class="form-control" %}
        
        <label class="font-custom" for="{{ form.telefono.id_for_label }}">{{ form.telefono.label_tag }}</label>
      </div>
    
      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.cellulare.errors %}
            {% render_field form.cellulare class="form-control is-invalid" %}
            {% for error in form.cellulare.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.cellulare class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.cellulare class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.cellulare.id_for_label }}">{{ form.cellulare.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
        {% if form.is_bound %}
          {% if form.email.errors %}
            {% render_field form.email class="form-control is-invalid" %}
            {% for error in form.email.errors  %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
              {% render_field form.email class="form-control is-valid" %}
          {% endif %}
        {% else %}
            {% render_field form.email class="form-control" %}
        {% endif %}
        <label class="font-custom" for="{{ form.email.id_for_label }}">{{ form.email.label_tag }}</label>
      </div>

      <div class="form-floating mb-3">
       
      </div> 

      <div class="form-floating mb-3">
      
        {% render_field form.note class="form-control" %}
    
        <label class="font-custom" for="{{ form.note.id_for_label }}">{{ form.note.label_tag }}</label>
      </div>

    </div>

    <div id = bottoni_griglia>

      <button id= 'button_crea' class="bottone_viola" type="submit"><p id = 'menu_text_button'> Modifica </p></button>
      <a href="{% url 'clienti:search_clienti' %}" id= 'button_esci' class="btn bottone_viola"><p id = 'menu_text_button'> Esci senza salvare </p></a>

    </div>
    </form>
  </div>

{% endblock %}
{% block script %}

  <script>
    $(document).ready(function() {

      $('#id_cognome').blur(codicefiscale);
      $('#id_nome').blur(codicefiscale);
      $('#id_sesso').on('change', codicefiscale);
      $('#id_citta_nascita').blur(codicefiscale);
      $('#id_data_nascita').blur(codicefiscale);

      function codicefiscale()
      {   
        
        cognome=$('#id_cognome').val();
        nome  =$('#id_nome').val();
        datan = $('#id_data_nascita').val();
        sesso =$('#id_sesso').val();
        comune = $('#id_citta_nascita').val();

        url = '{% url 'clienti:ajax_codice_fiscale' %}';
        
        if (cognome != "" && nome != "" && datan != ""  && sesso != "" && comune != "") {
          
          $.ajax({
              type: 'GET',
              url: url,
              data: {
              "cognome": cognome,
              "nome": nome,
              "data": datan,
              "sesso": sesso,
              "comune": comune,
              },
              success: function (data) {
      
                  $('#id_codice_fiscale').val(data.content);
              
              },
              error: function (data){

                  alert(data);

              }
            });
        }   
      }
    })
  </script>
  
{% endblock script %}