Myw8ForAesthetics/calendario/urls.py
from django.urls import path
from .views import appuntamenti, indice, aggiungi_appuntamento, rimuovi_appuntamento, modifica_appuntamento, conferma_appuntamento

app_name = 'calendario'


urlpatterns = [
    path('appuntamenti/', indice, name='appuntamenti'),
    path('listaappuntamenti/', appuntamenti, name='lista_appuntamenti'),
    path('add_event/', aggiungi_appuntamento
         , name='aggiungi_appuntamento'),
    path('remove_event/', rimuovi_appuntamento
         , name='rimuovi_appuntamento'),
    path('move_event/', modifica_appuntamento
         , name='modifica_appuntamento'),
    path('confirm_event/', conferma_appuntamento
         , name='conferma_appuntamento'),
    
    # Altre URL del tuo progetto Django...
]

Myw8ForAesthetics/clienti/urls.py
from django.urls import path
from .views import sceltamenu, sceltacliente, sceltapostcliente, sceltamisure
from .views import get_codice_fiscale, search_clienti
from .views import crea_cliente, crea_cliente_piva, crea_cliente_minore
from .views import info_cliente, modifica_cliente
from .views import crea_misura, riepilogo_misura, inviopcu, riepilogo_misura_elenco

app_name = 'clienti'

urlpatterns = [
    # Altre URL dell'applicazione...
    path('', sceltamenu, name='sceltamenu'),
    path('tipo', sceltacliente, name='tipocliente'),
    path('post', sceltapostcliente, name='postcliente'),
    path('misure',  sceltamisure, name='scelta_misure'),

    path('nuovo', crea_cliente, name='nuovocliente'),
    path('nuovopiva', crea_cliente_piva, name='nuovoclientepiva'),
    path('nuovominore', crea_cliente_minore, name='nuovoclienteminore'),

    path('nuovamisura', crea_misura, name='nuovamisura'),
    path('misurariepilogo/<int:id>/', riepilogo_misura,
         name='misure_riepilogo_clienti'),
    path('misurariepilogocliente/<int:id>/', riepilogo_misura_elenco,
         name='misure_riepilogo_clienti_elenco'),
    path('inviopcu/<int:id>/', inviopcu, name='inviopcu'),



    path('search/', search_clienti, name='search_clienti'),

    path('informazioni/<int:id>/', info_cliente, name='info_cliente'),
    path('modifica/<int:id>/', modifica_cliente, name='modifica_cliente'),

    path('ajax/cf', get_codice_fiscale, name='ajax_codice_fiscale'),


]

Myw8ForAesthetics/ordini/urls.py
from django.urls import path
from .views import sceltagruppo, sceltalistino, sceltapagamento, riassuntoinfo
from .views import misure_mancanti, modulodati_mancante, moduloalimenti_mancante, invio_moduli
from .views import invio_ordine, elenco_ordini
from .views import info_ordine

app_name = 'ordini'

urlpatterns = [

    path('sceltaprogramma/<int:id>/',  sceltagruppo, name='scelta_gruppo'),
    path('sceltapagamento/<int:id>/',  sceltapagamento, name='scelta_pagamento'),
    path('sceltalistino/<int:id>/<int:pg>',
         sceltalistino, name='scelta_listino'),
    path('riassuntoprogramma/<int:id>/',
         riassuntoinfo, name='riassunto_programma'),
    path('sceltalistino/',  misure_mancanti, name='misura_mancante'),
    path('invioordine/<int:id>',  invio_ordine, name='invio_ordine_mail'),
    path('inviomoduli/<int:id>',  invio_moduli, name='invio_moduli_mail'),
    path('inserimentodati/<int:id>',  modulodati_mancante, name='modulodati_mancante'),
    path('inserimentoalimenti/<int:id>',  moduloalimenti_mancante, name='moduloalimenti_mancante'),
    path('lista_ordini/',  elenco_ordini, name='lista_ordini'),
    path('infoordine/<int:id>',  info_ordine, name='info_ordine'),
]

Myw8ForAesthetics/utente/urls.py
from django.urls import path
from .views import login_view, homepagecentro, logout_view, logout_auto_view

app_name = 'utente'

urlpatterns = [
    # Altre URL dell'applicazione...
    path('login/', login_view, name='login'),
    path('homepage/centro', homepagecentro, name='homec'),
    path('logout/', logout_view, name='logout'),
    path('logout_auto/', logout_auto_view, name='logout-auto'),
]

Myw8ForAesthetics/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>{% block title %} {% endblock title %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/stilehome.css' %}" />
        {% block css %}

        {% endblock css %}

        <!-- script -->
        <script src = "https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        {% block scriptlibrerie %}

        {% endblock scriptlibrerie %}

        {% comment %}  {% endcomment %}
    </head>
    <body>

        <!-- barra laterale -->
            <div class="offcanvas offcanvas-start" id="demo">
                
            <div id ='pers1'class="col-auto px-sm-2 px-0">
                    <div class='sidenav-header'>
                        <div id = 'nav_logo_row'>
                        <img id= "image_barra"        
                        src= {% static '/static_file/logo_bianco.png' %}
                        alt="Immagine" />
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
                        
                    </div>

                    <hr class="horizontal dark">

                    <div >
                        <a href="#" class ="nav_user_link">
                            <img src="https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80" class="avatar avatar-sm">
                            <div class="ms-2">
                                <h6 class="text-sm mb-0">Andrew Millo</h6>
                            </div>
                        </a>
                    </div>

                    <hr class="horizontal dark">

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav_menu_link" href="{% url 'utente:homec' %}">                      
                                    <div class="icon">
                                        <img src={% static '/static_file/home.png' %} alt="Icona" width="20px" height="20px">
                                    </div>
                                    <div class="nav-link-text">Home</div>                     
                            </a>
                        </li>
                        <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav_menu_link" href="{% url 'clienti:sceltamenu' %}">                   
                                        <div class="icon">
                                            <img src={% static '/static_file/clienti.png' %} alt="Icona" width="20px" height="20px">
                                        </div>
                                        <div class="nav-link-text">Clienti</div>                           
                                </a>
                            </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav_menu_link" href="">                      
                                    <div class="icon">
                                        <img src={% static '/static_file/network.png' %} alt="Icona" width="20px" height="20px">
                                    </div>
                                    <div class="nav-link-text">Rete</div>                     
                            </a>
                        </li>
                        <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav_menu_link" href="{% url 'ordini:lista_ordini' %}">                   
                                        <div class="icon">
                                            <img src={% static '/static_file/accordi.png' %} alt="Icona" width="20px" height="20px">
                                        </div>
                                        <div class="nav-link-text">Ordini</div>                           
                                </a>
                            </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav_menu_link" href="">                      
                                    <div class="icon">
                                        <img src={% static '/static_file/provigioni.png' %} alt="Icona" width="20px" height="20px">
                                    </div>
                                    <div class="nav-link-text">Provigioni</div>                     
                            </a>
                        </li>
                        <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav_menu_link" href="">                   
                                        <div class="icon">
                                            <img src={% static '/static_file/listino.png' %} alt="Icona" width="20px" height="20px">
                                        </div>
                                        <div class="nav-link-text">Listini</div>                           
                                </a>
                            </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav_menu_link" href="{% url 'calendario:appuntamenti' %}">                      
                                    <div class="icon">
                                        <img src={% static '/static_file/calendar.png' %} alt="Icona" width="20px" height="20px">
                                    </div>
                                    <div class="nav-link-text">Calendario</div>                     
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav_menu_link" href="">                      
                                    <div class="icon">
                                        <img src={% static '/static_file/academy.png' %} alt="Icona" width="20px" height="20px">
                                    </div>
                                    <div class="nav-link-text">Academy</div>                     
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav_menu_link" href="">                      
                                    <div class="icon">
                                        <img src={% static '/static_file/chat.png' %} alt="Icona" width="20px" height="20px">
                                    </div>
                                    <div class="nav-link-text">Chat</div>                     
                            </a>
                        </li>          
                    </ul>

                    <hr class="horizontal dark">

                    <a class="nav_menu_link" href="{% url 'utente:logout' %}">                      
                        <div class="icon">
                            <img src={% static '/static_file/logout.png' %} alt="Icona" width="20px" height="20px">
                        </div>
                        <div class="nav-link-text">Logout</div>                     
                    </a>

                    <hr class="horizontal dark">

                    <div class="sidenav-footer mx-3 position-sticky bottom-2 ">
                
                        <h6 class="text-uppercase text-xs font-weight-bolder mt-4">Messaggi</h6>

                        <a href="#" class ="nav_user_chat">
                            <div class="position-relative">
                                <img src="https://images.unsplash.com/photo-1595152772835-219674b2a8a6?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTA3fHxwb3J0cmFpdHxlbnwwfDJ8MHx8&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=60" class="avatar avatar-sm shadow">
                                <span class="position-absolute top-100 start-100 mt-n1 ms-n1 translate-middle p-1 bg-success border border-white border-1 rounded-circle">
                                    <span class="visually-hidden">Online</span>
                                </span>
                            </div>
                            <span class="text-xs font-weight-bold ms-2">Alec Thomson</span>
                            <span class="badge bg-light text-secondary badge-sm text-xxs px-2 py-1 font-weight-bold border-circle ms-auto">5 +</span>
                        </a>

                        <a href="#" class ="nav_user_chat">
                            <div class="position-relative">
                                <img src="https://images.unsplash.com/photo-1485893086445-ed75865251e0?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fHBvcnRyYWl0fGVufDB8MnwwfHw%3D&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=60" class="avatar avatar-sm shadow">
                                <span class="position-absolute top-100 start-100 mt-n1 ms-n1 translate-middle p-1 bg-success border border-white border-1 rounded-circle">
                                    <span class="visually-hidden">Online</span>
                                </span>
                            </div>
                            <span class="text-xs font-weight-bold ms-2">Max Linarson</span>
                        </a>

                        <a href="#" class ="nav_user_chat">
                            <div class="position-relative">
                                <img src="https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cG9ydHJhaXR8ZW58MHwyfDB8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=60" class="avatar avatar-sm shadow">
                                <span class="position-absolute top-100 start-100 mt-n1 ms-n1 translate-middle p-1 bg-light border border-white border-1 rounded-circle">
                                    <span class="visually-hidden">Online</span>
                                </span>
                            </div>
                            <span class="text-xs font-weight-bold ms-2">Josa Irial</span>
                            <span class="badge bg-light text-secondary badge-sm text-xxs px-2 py-1 font-weight-bold border-circle ms-auto">
                                14
                            </span>
                        </a>       
                    </div>     
                </div> 
            </div>
        
        <!-- pagina -->
            
                <header>
                    <button id= 'button_side' class="button-17" type="button" data-bs-toggle="offcanvas" data-bs-target="#demo">
                        <p id = 'menu_text_button'> Menu </p>
                    </button>
                    {% block header %}{% endblock header%}
                    <button id= 'button_side' class="visually-hidden" type="button" >
                        <p id = 'menu_text_button'> Menu </p>
                    </button>
                </header>

                <img
                id="image_supdx"
                class="image_login"
                src={% static '/static_file/triangolosup.png' %}
                alt="Immagine"
                />


                {% block content %}{% endblock %}
              

                <footer>
                    <div id="footer_rect" >
                        <img
                        id="image_logo"
                        class="image_login"
                        src={% static '/static_file/logo.png' %}
                        alt="Immagine"
                        />
                    </div>
                </footer>
            

    </body>
    {% block script %}


    {% endblock script %}
    <script>
        
        window.addEventListener('unload', function() {
           
            $.ajax({
                url: "{% url 'utente:logout-auto' %}", // Sostituisci con l'URL della tua view Django
                type: 'GET',  // Puoi usare GET, POST o qualsiasi altro metodo HTTP necessario
                async: false,  // Usa async: true per consentire la richiesta asincrona
                success: function(data) {
                   
                },
                error: function(error) {
                  
                }         
               });
            
            debugger;
        });
        
        
    </script>
</html>
          