Myw8ForAesthetics/calendario/urls.py
from django.urls import path
from .views import appuntamenti, indice, aggiungi_appuntamento, rimuovi_appuntamento, modifica_appuntamento, conferma_appuntamento

app_name = 'calendario'


urlpatterns = [
    path('appuntamenti/', indice, name='appuntamenti'),
    path('listaappuntamenti/', appuntamenti, name='lista_appuntamenti'),
    path('add_event/', aggiungi_appuntamento
         , name='aggiungi_appuntamento'),
    path('remove_event/', rimuovi_appuntamento
         , name='rimuovi_appuntamento'),
    path('move_event/', modifica_appuntamento
         , name='modifica_appuntamento'),
    path('confirm_event/', conferma_appuntamento
         , name='conferma_appuntamento'),
    
    # Altre URL del tuo progetto Django...
]

Myw8ForAesthetics/ordini/urls.py
from django.urls import path
from .views import sceltagruppo, sceltalistino, sceltapagamento, riassuntoinfo
from .views import misure_mancanti, modulodati_mancante, moduloalimenti_mancante, invio_moduli
from .views import invio_ordine, elenco_ordini
from .views import info_ordine

app_name = 'ordini'

urlpatterns = [

    path('sceltaprogramma/<int:id>/',  sceltagruppo, name='scelta_gruppo'),
    path('sceltapagamento/<int:id>/',  sceltapagamento, name='scelta_pagamento'),
    path('sceltalistino/<int:id>/<int:pg>',
         sceltalistino, name='scelta_listino'),
    path('riassuntoprogramma/<int:id>/',
         riassuntoinfo, name='riassunto_programma'),
    path('sceltalistino/',  misure_mancanti, name='misura_mancante'),
    path('invioordine/<int:id>',  invio_ordine, name='invio_ordine_mail'),
    path('inviomoduli/<int:id>',  invio_moduli, name='invio_moduli_mail'),
    path('inserimentodati/<int:id>',  modulodati_mancante, name='modulodati_mancante'),
    path('inserimentoalimenti/<int:id>',  moduloalimenti_mancante, name='moduloalimenti_mancante'),
    path('lista_ordini/',  elenco_ordini, name='lista_ordini'),
    path('infoordine/<int:id>',  info_ordine, name='info_ordine'),
]

Myw8ForAesthetics/calendario/models.py
from django.db import models

# Create your models here.

Myw8ForAesthetics/calendario/views.py
from django.shortcuts import render
from django.http import JsonResponse

from django.conf import settings

import requests

import pdb


def appuntamenti(request):
    
    # Effettua la richiesta POST all'API
    url_backend = settings.BASE_URL + 'calendario/crea_appuntamento/'
    headers = {
        "Authorization": f"Token {request.session['auth_token']}"
    }

    response = requests.get(url_backend, headers=headers)
    if response.status_code == 200:
        appuntamenti = response.json()
    
    events = []

    for appuntamento in appuntamenti:
        events.append({
            'title': appuntamento['titolo'],
            'start': appuntamento['inizio'],
            'end': appuntamento['fine'],
            'id': appuntamento['id'],
            'descrizione': appuntamento['descrizione'],
            'effettuato': appuntamento['effettuato']
        })
        
    print(events)
    return JsonResponse(events, safe=False)

def indice(request):  
    
    url_backend = settings.BASE_URL + 'calendario/crea_appuntamento/'
    headers = {
        "Authorization": f"Token {request.session['auth_token']}"
    }

    response = requests.get(url_backend, headers=headers)
    if response.status_code == 200:
        appuntamenti = response.json()
    context = {
        "events":appuntamenti,
    }
    return render(request,'calendario/calendario.html',context)
 

 
def aggiungi_appuntamento(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    description = request.GET.get("description", None)
    
    if end is None:
        end = start
    print(end)
    url_backend = settings.BASE_URL + 'calendario/crea_appuntamento/'
    headers = {
        "Authorization": f"Token {request.session['auth_token']}"
    }

    data = {
        'titolo' : title,
        'inizio' : start,
        'fine' : end,
        'descrizione' : description
         
    }
    
    
    response = requests.post(url_backend, data=data, headers=headers)
    if response.status_code == 200:
        appuntamenti = response.json()
    
    data = {}
    return JsonResponse(data)
 
# def update(request):
#     start = request.GET.get("start", None)
#     end = request.GET.get("end", None)
#     title = request.GET.get("title", None)
#     id = request.GET.get("id", None)
#     event = Events.objects.get(id=id)
#     event.start = start
#     event.end = end
#     event.name = title
#     event.save()
#     data = {}
#     return JsonResponse(data)
 
def rimuovi_appuntamento(request):
    id = request.GET.get("id", None)
    
    url_backend = settings.BASE_URL + 'calendario/elimina_appuntamento/' + str(id)
    headers = {
        "Authorization": f"Token {request.session['auth_token']}"
    }
    
    response = requests.delete(url_backend, headers=headers)
    data = {}
    return JsonResponse(data)

def modifica_appuntamento(request):
    id = request.GET.get("id", None)
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    
    url_backend = settings.BASE_URL + 'calendario/appuntamento/' + str(id) +'/'
    headers = {
        "Authorization": f"Token {request.session['auth_token']}"
    }
    if end == '':
        data = {
            'id' : id,
            'inizio' : start,
            
            
        }
    else:
         data = {
            'id' : id,
            'inizio' : start,
            'fine' : end,
            
        }
    response = requests.patch(url_backend, data=data, headers=headers)
    data = {}
    return JsonResponse(data)

def conferma_appuntamento(request):
    id = request.GET.get("id", None)
    
    url_backend = settings.BASE_URL + 'calendario/appuntamento/' + str(id) +'/'
    headers = {
        "Authorization": f"Token {request.session['auth_token']}"
    }
    
    data = {
        'id' : id,
        'effettuato' : True
        
    }
    
    
    response = requests.patch(url_backend, data=data, headers=headers)
    data = {}
    return JsonResponse(data)
    
    

Myw8ForAesthetics/calendario/templates/calendario/c2.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Appuntamenti {% endblock title %}
{% block header %}

<div id="text_header_rect" class = 'purple_rect'>
    <p id="text_header" class="text"> Appuntamenti </p>
</div>

{% endblock header%}
{% block css %}
    
{% endblock css %}
{% block scriptlibrerie %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/6.1.10/index.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/6.1.10/index.global.js'></script>
    <script src=https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/locales/it.js></script>
    <link rel="stylesheet" href="{% static 'css/agenda.css' %}" />
   
{% endblock scriptlibrerie %}
{% block content %}
<div class="container">
    <div class="row">
      
            <div id='calendar'></div> 
       </div> 
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            headerToolbar: {
              left: 'prev,next today',
              center: 'title',
              right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
            },
            locale: 'it',
            buttonIcons: false, // show the prev/next text
            weekNumbers: false,
            navLinks: true, // can click day/week names to navigate views
            editable: true,
            dayMaxEvents: true, // allow "more" link when too many events
            themeSystem: 'bootstrap5',
            slotMinTime: '07:00',
            slotMaxTime: '21:00',
            events: '/calendario/',

            dateClick: function(start, end, allDay) {
                var title = prompt("Aggiungi Appuntamento");
                if (title) {
                    var start = $.fullCalendar.formatDate(start, "Y-MM-DD HH:mm:ss");
                    var end = $.fullCalendar.formatDate(end, "Y-MM-DD HH:mm:ss");
                    $.ajax({
                        type: "GET",
                        url: '/add_event',
                        data: {'title': title, 'start': start, 'end': end},
                        dataType: "json",
                        success: function (data) {
                            calendar.fullCalendar('refetchEvents');
                            alert("Added Successfully");
                        },
                        error: function (data) {
                            alert('There is a problem!!!');
                        }
                    });
                }
            },
          });
        
          calendar.render();
        });
 </script>

  
{% endblock script %}

Myw8ForAesthetics/calendario/templates/calendario/calendario.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Appuntamenti {% endblock title %}
{% block header %}

<div id="text_header_rect" class = 'purple_rect'>
    <p id="text_header" class="text"> Appuntamenti </p>
</div>

{% endblock header%}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/agenda.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.5/dist/sweetalert2.min.css">
{% endblock css %}
{% block scriptlibrerie %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/6.1.10/index.global.js'></script>

    <script src=https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/locales/it.js></script>
    
    <script src = "https://unpkg.com/tooltip.js/dist/umd/tooltip.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.5/dist/sweetalert2.all.min.js"></script>
    
   
{% endblock scriptlibrerie %}
{% block content %}
<div class="container">
    <div class="row">
      
            <div id='calendar'></div> 
       </div> 
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            headerToolbar: {
              left: 'prev,next today',
              center: 'title',
              right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
            },
            selectable: true,
            locale: 'it',
            buttonIcons: false, // show the prev/next text
            weekNumbers: false,
            navLinks: true, // can click day/week names to navigate views
            editable: true,
            dayMaxEvents: true, // allow "more" link when too many events
            themeSystem: 'bootstrap5',
            defaultTimedEventDuration: '00:30:00',
            minTime: '07:00:00',
            slotMinTime: '07:00',
            slotMaxTime: '21:00',
            eventSources: [
            // your event source
            {
              url: '{% url 'calendario:lista_appuntamenti' %}', // use the `url` property
              color: '#d7d4de',    // an option!
              textColor: 'black'  // an option!
            }  
          ],

        
            
          dateClick: function(info) {
            Swal.fire({
                title: 'Aggiungi Appuntamento',
                html:
                    '<input id="swal-input1" class="swal2-input" placeholder="Inserisci il titolo">' +
                    '<input id="swal-input2" class="swal2-input" placeholder="Inserisci la descrizione">',
                showCancelButton: true,
                confirmButtonText: 'Inserisci', 
                cancelButtonText: 'Chiudi',
                confirmButtonColor: '#83719c',
                cancelButtonColor: '#83719c',
                focusConfirm: false,
                preConfirm: () => {
                    const title = Swal.getPopup().querySelector('#swal-input1').value;
                    const description = Swal.getPopup().querySelector('#swal-input2').value;
        
                    if (!title) {
                        Swal.showValidationMessage('Il titolo è obbligatorio');
                    }
        
                    return { title, description };
                },
                customClass: {
                    confirmButton: 'custom-confirm-button', // Aggiungi la tua classe CSS per il pulsante "Aggiungi"
                    cancelButton: 'custom-cancel-button' // Aggiungi la tua classe CSS per il pulsante "Chiudi"
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    var start = info.dateStr;
                    $.ajax({
                        type: "GET",
                        url: '{% url 'calendario:aggiungi_appuntamento' %}',
                        data: {'title': result.value.title, 'start': start, 'description': result.value.description},
                        dataType: "json",
                        success: function (data) {
                            calendar.refetchEvents();
                            Swal.fire('Aggiunto con successo!', '', 'success');
                        },
                        error: function (data) {
                            Swal.fire('Errore!', 'Si è verificato un problema!', 'error');
                        }
                    });
                }
            });
        },
        
        

        select: function(info) {
            Swal.fire({
                title: 'Aggiungi Appuntamento',
                html:
                    '<input id="swal-input1" class="swal2-input" placeholder="Inserisci il titolo">' +
                    '<input id="swal-input2" class="swal2-input" placeholder="Inserisci la descrizione">',
                
                showCancelButton: true,
                confirmButtonText: 'Inserisci', 
                cancelButtonText: 'Chiudi',
                confirmButtonColor: '#83719c',
                cancelButtonColor: '#83719c',
                focusConfirm: false,
                preConfirm: () => {
                    const title = Swal.getPopup().querySelector('#swal-input1').value;
                    const description = Swal.getPopup().querySelector('#swal-input2').value;
        
                    if (!title) {
                        Swal.showValidationMessage('Il titolo è obbligatorio');
                    }
        
                    return { title, description };
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    var start = info.startStr;
                    var end = info.endStr;
                    $.ajax({
                        type: "GET",
                        url: '{% url 'calendario:aggiungi_appuntamento' %}',
                        data: {'title': result.value.title, 'start': start, 'end': end, 'description': result.value.description},
                        dataType: "json",
                        success: function (data) {
                            calendar.refetchEvents();
                            Swal.fire('Aggiunto con successo!', '', 'success');
                        },
                        error: function (data) {
                            Swal.fire('Errore!', 'Si è verificato un problema!', 'error');
                        }
                    });
                }
            });
        },
        

        eventClick: function(info) {
            var id = info.event.id;
        
            Swal.fire({
                title: 'Conferma o Cancella?',
                text: 'Scegli se confermare l\'appuntamento o cancellarlo.',
                icon: 'question',
                showCancelButton: true,
                showDenyButton: true,
                confirmButtonColor: '#83719c',
                cancelButtonColor: '#83719c',
                denyButtonColor: '#83719c',
                confirmButtonText: 'Appuntamento Effettuato',
                cancelButtonText: 'Cancella Appuntamento',
                denyButtonText: `Annulla`,
               
            }).then((result) => {
                if (result.isConfirmed) {
                    // Effettua la conferma
                    $.ajax({
                        type: "GET",
                        url: '{% url 'calendario:conferma_appuntamento' %}',
                        data: {'id': id},
                        dataType: "json",
                        success: function (data) {
                            calendar.refetchEvents();
                            Swal.fire('Confermato!', 'L\'appuntamento è stato confermato con successo.', 'success');
                        },
                        error: function (data) {
                            Swal.fire('Errore!', 'Si è verificato un problema durante la conferma dell\'appuntamento.', 'error');
                        }
                    });
                } else if (result.dismiss === Swal.DismissReason.cancel) {
                    // Cancella l'appuntamento
                    $.ajax({
                        type: "GET",
                        url: '{% url 'calendario:rimuovi_appuntamento' %}',
                        data: {'id': id},
                        dataType: "json",
                        success: function (data) {
                            calendar.refetchEvents();
                            Swal.fire('Rimosso!', 'L\'appuntamento è stato rimosso con successo.', 'success');
                        },
                        error: function (data) {
                            Swal.fire('Errore!', 'Si è verificato un problema durante la rimozione.', 'error');
                        }
                    });
                } 
            });
        },
        

        eventDidMount: function(info) {
           
            $(info.el).popover({
                
                title: info.event.title,
                placement: 'top',
                trigger: 'hover',
                content: info.event.extendedProps.descrizione,
                container: 'body'
            });
    
            if (info.event.extendedProps.effettuato == true)
            {
                $(info.el).find(".fc-list-event-dot").css('border-color','#2a7568'); 
                $(info.el).find(".fc-daygrid-event-dot").css('border-color','#2a7568');
                $(info.el).find(".fc-event-main").css('color','#2a7568');
                }
           
          },

        eventDrop: function(info) {
      
            var id = info.event.id;
            var start = info.event.startStr;
            var end = info.event.endStr;

            $('.popover').remove();
        
                    $.ajax({
                        type: "GET",
                        url: '{% url 'calendario:modifica_appuntamento' %}',
                        data: {'id': id, 'start': start, 'end': end},
                        dataType: "json",
                        success: function (data) {
                            calendar.refetchEvents();
                            
                        },
                        error: function (data) {                        
                        }
                    });
        },

    
        
    });

       
        
          calendar.render();
        });
 </script>

  
{% endblock script %}