Myw8ForAesthetics/clienti/urls.py
from django.urls import path
from .views import sceltamenu, sceltacliente, sceltapostcliente, sceltamisure
from .views import get_codice_fiscale, search_clienti
from .views import crea_cliente, crea_cliente_piva, crea_cliente_minore
from .views import info_cliente, modifica_cliente
from .views import crea_misura, riepilogo_misura, inviopcu, riepilogo_misura_elenco

app_name = 'clienti'

urlpatterns = [
    # Altre URL dell'applicazione...
    path('', sceltamenu, name='sceltamenu'),
    path('tipo', sceltacliente, name='tipocliente'),
    path('post', sceltapostcliente, name='postcliente'),
    path('misure',  sceltamisure, name='scelta_misure'),

    path('nuovo', crea_cliente, name='nuovocliente'),
    path('nuovopiva', crea_cliente_piva, name='nuovoclientepiva'),
    path('nuovominore', crea_cliente_minore, name='nuovoclienteminore'),

    path('nuovamisura', crea_misura, name='nuovamisura'),
    path('misurariepilogo/<int:id>/', riepilogo_misura,
         name='misure_riepilogo_clienti'),
    path('misurariepilogocliente/<int:id>/', riepilogo_misura_elenco,
         name='misure_riepilogo_clienti_elenco'),
    path('inviopcu/<int:id>/', inviopcu, name='inviopcu'),



    path('search/', search_clienti, name='search_clienti'),

    path('informazioni/<int:id>/', info_cliente, name='info_cliente'),
    path('modifica/<int:id>/', modifica_cliente, name='modifica_cliente'),

    path('ajax/cf', get_codice_fiscale, name='ajax_codice_fiscale'),


]

Myw8ForAesthetics/ordini/urls.py
from django.urls import path
from .views import sceltagruppo, sceltalistino, sceltapagamento, riassuntoinfo
from .views import misure_mancanti, modulodati_mancante, moduloalimenti_mancante, invio_moduli
from .views import invio_ordine, elenco_ordini
from .views import info_ordine

app_name = 'ordini'

urlpatterns = [

    path('sceltaprogramma/<int:id>/',  sceltagruppo, name='scelta_gruppo'),
    path('sceltapagamento/<int:id>/',  sceltapagamento, name='scelta_pagamento'),
    path('sceltalistino/<int:id>/<int:pg>',
         sceltalistino, name='scelta_listino'),
    path('riassuntoprogramma/<int:id>/',
         riassuntoinfo, name='riassunto_programma'),
    path('sceltalistino/',  misure_mancanti, name='misura_mancante'),
    path('invioordine/<int:id>',  invio_ordine, name='invio_ordine_mail'),
    path('inviomoduli/<int:id>',  invio_moduli, name='invio_moduli_mail'),
    path('inserimentodati/<int:id>',  modulodati_mancante, name='modulodati_mancante'),
    path('inserimentoalimenti/<int:id>',  moduloalimenti_mancante, name='moduloalimenti_mancante'),
    path('lista_ordini/',  elenco_ordini, name='lista_ordini'),
    path('infoordine/<int:id>',  info_ordine, name='info_ordine'),
]

Myw8ForAesthetics/amministrazione/models.py
from django.db import models
from consulenti.models import AnagraficaConsulente
from accordi.models import Programmi
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
def incremento_accordo():

    ultimo = AccordoNumero.objects.order_by('id').last()
    obj = datetime.now().year
    anno = str(obj)

    if not ultimo:  # aggiungere reset al nuovo anno

        return '0001' + '/' + anno

    numero_ordine = ultimo.numero_accordo
    numero_ordine_intero = int(numero_ordine.split('/')[0])
    new_numero_ordine = numero_ordine_intero + 1
    new_numero_ordine_stringa = str(new_numero_ordine) + '/' + anno

    return new_numero_ordine_stringa


class AccordoNumero(models.Model):

    numero_accordo = models.CharField(
        max_length=10, default=incremento_accordo)
    tipo_accordo = models.CharField(max_length=100)

    def __str__(self):
        return self.numero_accordo

    class Meta:
        verbose_name = "Numero Accordo"
        verbose_name_plural = "Numeri Accordi"


def incremento_accordo_corner():

    ultimo = AccordoNumeroCorner.objects.order_by('id').last()
    obj = datetime.now().year
    anno = str(obj)

    if not ultimo:  # aggiungere reset al nuovo anno

        return '0051'

    numero_ordine = ultimo.numero_accordo
    numero_ordine_intero = int(numero_ordine)
    new_numero_ordine = numero_ordine_intero + 1
    new_numero_ordine_stringa = str(new_numero_ordine)

    return new_numero_ordine_stringa


class AccordoNumeroCorner(models.Model):

    numero_accordo = models.CharField(
        max_length=10, default=incremento_accordo_corner)
    tipo_accordo = models.CharField(max_length=100)

    def __str__(self):
        return self.numero_accordo

    class Meta:
        verbose_name = "Numero Accordo Corner"
        verbose_name_plural = "Numeri Accordi Corner"


class Ordine(models.Model):

    MODALITA = (

        ('Integrale', 'Saldo Immediato'),
        ('Rateale', 'Pagamento Rateale'),
        ('Finanziato', 'Pagamento attraverso finanziaria')
    )

    STATO = (

        ('Inserito', 'Inserito nel sistema'),
        ('Attesa', 'Attesa del Pagamento'),
        ('Attivato', 'Ordine in lavorazione'),
        ('Sospeso', 'Ordine Sospeso')
    )

    cliente = models.ForeignKey(
        to='clienti.AnagraficaCliente', on_delete=models.PROTECT)
    consulente = models.ForeignKey(
        AnagraficaConsulente, on_delete=models.PROTECT)
    numero_ordine = models.ForeignKey(AccordoNumero, on_delete=models.PROTECT)
    utente_inserimento = models.ForeignKey(User, on_delete=models.PROTECT)
    validita_per_bilanciamento = models.BooleanField(
        default=False, null=True, blank=True)
    """Indirizzo Spedizione"""
    indirizzo = models.CharField(max_length=100)
    numero_civico = models.CharField(max_length=5, null=True)
    cap = models.CharField(max_length=5)
    citta = models.CharField(max_length=25)

    """ Date """
    data_creazione = models.DateTimeField()
    data_ultima_modifica = models.DateTimeField(blank=True, null=True)
    utente_ultima_modifica = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='utente_modifica', blank=True, null=True)
    data_pagamento_ordine = models.DateField(blank=True, null=True)
    """ Pagamenti """
    modalita_pagamento = models.CharField(max_length=50, choices=MODALITA)
    importo_acconto = models.DecimalField(
        max_digits=7, decimal_places=2, blank=True, null=True)
    numero_rate = models.IntegerField(blank=True, null=True)
    mesi_tra_le_rate = models.IntegerField(blank=True, null=True)
    importo_rata = models.DecimalField(
        max_digits=7, decimal_places=2, blank=True, null=True)

    """ Stato Ordine"""

    stato_ordine = models.CharField(max_length=50, choices=STATO)

    def __str__(self):
        return str(self.numero_ordine.numero_accordo) + "-" + str(self.cliente)

    class Meta:
        verbose_name = "Ordine"
        verbose_name_plural = "Ordini"


class DettaglioOrdini(models.Model):

    ordine = models.ForeignKey(Ordine, on_delete=models.PROTECT)

    """ Listino """

    chiave_listino = models.CharField(max_length=5, blank=False, null=False)
    nome_listino = models.CharField(max_length=50, blank=False, null=False)
    descrizione_programma = models.CharField(
        max_length=250, blank=False, null=False)
    importo = models.DecimalField(max_digits=10, decimal_places=2)

    """ Prezzo """
    gratuita = models.BooleanField(default=False)
    iva = models.IntegerField(blank=True, null=True)
    imponibile = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return str(self.ordine) + self.nome_listino

    class Meta:
        verbose_name = "Dettaglio Ordine"
        verbose_name_plural = "Dettaglio Ordini"


class EmailAzienda(models.Model):

    descrizione = models.CharField(max_length=50)
    email = models.EmailField(max_length=150, blank=True, null=True)
    testo_oggetto = models.CharField(max_length=50)
    testo_mail = models.TextField(blank=True, null=True)
    bcc = models.EmailField(max_length=150, blank=True, null=True)
    bcc2 = models.EmailField(max_length=150, blank=True, null=True)

    def __str__(self):
        return self.descrizione

    class Meta:
        verbose_name = "Email Azienda"
        verbose_name_plural = "Email Azienda"


class Costanti(models.Model):

    valore = models.CharField(max_length=20)
    descrizione = models.CharField(max_length=50)

    def __str__(self):
        return self.descrizione

    class Meta:
        verbose_name = "Costante"
        verbose_name_plural = "Costanti"


class FileCaricabili(models.Model):

    tipodifile = models.CharField(max_length=20)
    descrizione = models.CharField(max_length=50)
    profiloutente = models.ForeignKey(
        to='consulenti.RuoliConsulente', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.tipodifile.replace('_', ' ')

    class Meta:
        verbose_name = "File Caricabile"
        verbose_name_plural = "File Caricabili"


class AnagraficaProvvigioni(models.Model):

    tipo_consulente = models.ForeignKey(
        to='consulenti.RuoliConsulente', on_delete=models.CASCADE)
    consulente_partner = models.ForeignKey(
        to='consulenti.AnagraficaConsulente', on_delete=models.CASCADE, null=True, blank=True)
    linea = models.CharField(max_length=3, null=True, blank=True)
    importo_linea = models.CharField(max_length=10, null=True, blank=True)
    percentuale = models.CharField(max_length=3, null=True, blank=True)
    listino = models.ForeignKey(
        to='accordi.Programmi', on_delete=models.CASCADE)
    rete = models.ForeignKey(to='consulenti.Struttura',
                             on_delete=models.CASCADE, default=1)
    data_inizio_validita = models.DateTimeField(null=True, blank=True)
    data_fine_validita = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.listino) + ' ' + str(self.tipo_consulente)

    class Meta:
        verbose_name = "Anagrafica Provvigione"
        verbose_name_plural = "Anagrafica Provvigioni"


class CodiciIva(models.Model):

    nome = models.CharField(max_length=3)
    valore = models.IntegerField()
    descrizione = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Codice Iva"
        verbose_name_plural = "Codici Iva"


class Scadenze(models.Model):

    STATO = (

        ('Pagato', 'Pagamento Inserito'),
        ('Non Pagato', 'In Attesa del Pagamento')
    )

    cliente = models.ForeignKey(
        to='clienti.AnagraficaCliente', on_delete=models.PROTECT)
    consulente = models.ForeignKey(
        AnagraficaConsulente, on_delete=models.PROTECT)
    numero_ordine = models.ForeignKey(AccordoNumero, on_delete=models.PROTECT)

    """ Date modifica """
    data_creazione = models.DateTimeField(auto_now_add=True)
    data_scadenza = models.DateField()
    data_pagamento_ordine = models.DateField(null=True, blank=True)

    """ Pagamenti """
    importo = models.DecimalField(max_digits=9, decimal_places=2)

    """ Stato Ordine"""
    stato_ordine = models.CharField(max_length=20, choices=STATO)

    def __str__(self):
        return str(self.numero_ordine.numero_accordo) + "-" + str(self.data_scadenza) + "-" + self.cliente.cognome

    class Meta:
        verbose_name = "Scadenza"
        verbose_name_plural = "Scadenze"


class Documentazione(models.Model):

    nome_documento = models.CharField(max_length=60, null=True, blank=True)
    descrizione_documento = models.CharField(max_length=30)
    percorso = models.CharField(max_length=100)
    data_caricamento = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome_documento

    class Meta:
        verbose_name = "Documento"
        verbose_name_plural = "Documenti"


class Alimenti(models.Model):

    CLASSE = (
        ('Legumi', 'Legumi'),
        ('Latticini', 'Latticini'),
        ('Frutta secca', 'Frutta secca'),
        ('Uovo', 'Uovo'),
        ('Tacchino', 'Tacchino'),
        ('Manzo', 'Manzo'),
        ('Maiale', 'Maiale'),
        ('Coniglio', 'Coniglio'),
        ('Vitello', 'Vitello'),
        ('Agnello', 'Agnello'),
        ('Frutta', 'Frutta'),
        ('Verdura', 'Verdura'),
        ('Pesce', 'Pesce'),
        ('Pollo', 'Pollo'),
        ('Crostacei', 'Crostacei'),
        ('Molluschi', 'Molluschi'),
    )

    nome = models.CharField(max_length=50)
    classe_alimenti = models.CharField(max_length=25, choices=CLASSE)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Alimento"
        verbose_name_plural = "Alimenti"

Myw8ForAesthetics/ordini/models.py
from django.db import models






# # Create your models here.
# class Ordine(models.Model):

#     MODALITA = (

#         ('Integrale', 'Saldo Immediato'),
#         ('Rateale', 'Pagamento Rateale'),
#         ('Finanziato', 'Pagamento attraverso finanziaria')
#     )

#     STATO = (

#         ('Inserito', 'Inserito nel sistema'),
#         ('Attesa', 'Attesa del Pagamento'),
#         ('Attivato', 'Ordine in lavorazione'),
#         ('Sospeso', 'Ordine Sospeso')
#     )

#     cliente = models.ForeignKey(
#         to='clienti.AnagraficaCliente', on_delete=models.PROTECT)
#     consulente = models.ForeignKey(
#         AnagraficaConsulente, on_delete=models.PROTECT)
#     numero_ordine = models.ForeignKey(AccordoNumero, on_delete=models.PROTECT)
#     utente_inserimento = models.ForeignKey(User, on_delete=models.PROTECT)
#     validita_per_bilanciamento = models.BooleanField(
#         default=False, null=True, blank=True)
#     """Indirizzo Spedizione"""
#     indirizzo = models.CharField(max_length=100)
#     numero_civico = models.CharField(max_length=5, null=True)
#     cap = models.CharField(max_length=5)
#     citta = models.CharField(max_length=25)

#     """ Date """
#     data_creazione = models.DateTimeField()
#     data_ultima_modifica = models.DateTimeField(blank=True, null=True)
#     utente_ultima_modifica = models.ForeignKey(
#         User, on_delete=models.PROTECT, related_name='utente_modifica', blank=True, null=True)
#     data_pagamento_ordine = models.DateField(blank=True, null=True)
#     """ Pagamenti """
#     modalita_pagamento = models.CharField(max_length=50, choices=MODALITA)
#     importo_acconto = models.DecimalField(
#         max_digits=7, decimal_places=2, blank=True, null=True)
#     numero_rate = models.IntegerField(blank=True, null=True)
#     mesi_tra_le_rate = models.IntegerField(blank=True, null=True)
#     importo_rata = models.DecimalField(
#         max_digits=7, decimal_places=2, blank=True, null=True)

#     """ Stato Ordine"""

#     stato_ordine = models.CharField(max_length=50, choices=STATO)

#     def __str__(self):
#         return str(self.numero_ordine.numero_accordo) + "-" + str(self.cliente)

#     class Meta:
#         verbose_name = "Ordine"
#         verbose_name_plural = "Ordini"


# class DettaglioOrdini(models.Model):

#     ordine = models.ForeignKey(Ordine, on_delete=models.PROTECT)

#     """ Listino """

#     chiave_listino = models.CharField(max_length=5, blank=False, null=False)
#     nome_listino = models.CharField(max_length=50, blank=False, null=False)
#     descrizione_programma = models.CharField(
#         max_length=250, blank=False, null=False)
#     importo = models.DecimalField(max_digits=10, decimal_places=2)

#     """ Prezzo """
#     gratuita = models.BooleanField(default=False)
#     iva = models.IntegerField(blank=True, null=True)
#     imponibile = models.DecimalField(
#         max_digits=10, decimal_places=2, blank=True, null=True)

#     def __str__(self):
#         return str(self.ordine) + self.nome_listino

#     class Meta:
#         verbose_name = "Dettaglio Ordine"
#         verbose_name_plural = "Dettaglio Ordini"

Myw8ForAesthetics/ordini/templates/ordini/informazione_ordine.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Info Clienti {% endblock title %}
{% block header %}
<div id="text_header_rect" class = 'purple_rect'>
    <p id="text_header" class="text"> Informazioni Programma </p>
</div> 

{% endblock header%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/formgrid.css' %}" />
{% endblock css %}
{% block scriptlibrerie %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
{% endblock scriptlibrerie %}

{% block content %}
   
<div class="form-container">
  
   
    <div class ='grid_programma'>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Nome Programma </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Durata </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Importo </p></div>
        
        <div  class="bottone_viola_info"><p class = 'info_text_button'> {{programma.nome_programma}} </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> {{programma.durata_programma}} </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button' id = 'totale'> {{programma.importo_programma}} </p></div>
        
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Programma Kids </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Programma Rateale </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Programma Proseguimento </p></div>
        
        <div  class="bottone_viola_info">
            <p class = 'info_text_button'> {% if programma.programma_kids %} Si {% else %} No {% endif %}
             </p>
        </div>
        <div  class="bottone_viola_info">
            <p class = 'info_text_button'> {% if programma.programma_rateale %} Si {% else %} No {% endif %}
            </p>
        </div>
        <div  class="bottone_viola_info">
            <p class = 'info_text_button'> {% if programma.programma_proseguimento %} Si {% else %} No {% endif %}
            </p>
        </div>
    </div>
   
        <div id = 'bottoni_griglia'>
            {% comment %} <a href="{% url 'clienti:search_clienti' %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla lista clienti </p></a>
            <a href="{% url 'ordini:scelta_gruppo' id_cliente %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla selezione del programma </p></a>
            <a href="{% url 'ordini:scelta_pagamento' programma.gruppo %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla modalità di pagamento </p></a>
            <a href="{% url 'ordini:scelta_listino' programma.gruppo rat %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla selezione della durata </p></a>
     {% endcomment %}
        </div>
  
</div>

{% endblock %}
{% block script %}

  <script>
  
 
  </script>
  
{% endblock script %}

Myw8ForAesthetics/ordini/templates/ordini/riassunto_ordine.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Info Clienti {% endblock title %}
{% block header %}
<div id="text_header_rect" class = 'purple_rect'>
    <p id="text_header" class="text"> Informazioni Programma </p>
</div> 

{% endblock header%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/formgrid.css' %}" />
{% endblock css %}
{% block scriptlibrerie %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
{% endblock scriptlibrerie %}

{% block content %}
   
<div class="form-container">
  
   
    <div class ='grid_programma'>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Nome Programma </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Durata </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Importo </p></div>
        
        <div  class="bottone_viola_info"><p class = 'info_text_button'> {{programma.nome_programma}} </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> {{programma.durata_programma}} </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button' id = 'totale'> {{programma.importo}} </p></div>
        
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Programma Kids </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Programma Rateale </p></div>
        <div  class="bottone_viola_info"><p class = 'info_text_button'> Programma Proseguimento </p></div>
        
        <div  class="bottone_viola_info">
            <p class = 'info_text_button'> {% if programma.programma_kids %} Si {% else %} No {% endif %}
             </p>
        </div>
        <div  class="bottone_viola_info">
            <p class = 'info_text_button'> {% if programma.programma_rateale %} Si {% else %} No {% endif %}
            </p>
        </div>
        <div  class="bottone_viola_info">
            <p class = 'info_text_button'> {% if programma.programma_proseguimento %} Si {% else %} No {% endif %}
            </p>
        </div>
    </div>
    <form  method="post" novalidate>{% csrf_token %}
        {% if programma.programma_rateale %}
        <div  class="bottone_viola_info" id ="programma"><p class = 'info_text_button'> Informazioni per il pagamento rateale </p></div>
        <div class="grid-form_programma" >
             <div class="form-floating mb-3">
                {% if form.is_bound %}
                {% if form.acconto.errors %}
                    {% render_field form.acconto class="form-control is-invalid" %}
                    {% for error in form.acconto.errors  %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.acconto class="form-control is-valid" %}
                {% endif %}
                {% else %}
                    {% render_field form.acconto class="form-control" %}
                {% endif %}
                <label class="font-custom" for="{{ form.acconto.id_for_label }}">{{ form.acconto.label_tag }}</label>
            </div>

            <div class="form-floating mb-3">
                {% if form.is_bound %}
                {% if form.rate.errors %}
                    {% render_field form.rate class="form-control is-invalid" %}
                    {% for error in form.rate.errors  %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.rate class="form-control is-valid" %}
                {% endif %}
                {% else %}
                    {% render_field form.rate class="form-control" %}
                {% endif %}
                <label class="font-custom" for="{{ form.rate.id_for_label }}">{{ form.rate.label_tag }}</label>
            </div>

            <div class="form-floating mb-3">
                {% if form.is_bound %}
                {% if form.importo_rata.errors %}
                    {% render_field form.importo_rata class="form-control is-invalid" %}
                    {% for error in form.importo_rata.errors  %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.importo_rata class="form-control is-valid" %}
                {% endif %}
                {% else %}
                    {% render_field form.importo_rata class="form-control" %}
                {% endif %}
                <label class="font-custom" for="{{ form.importo_rata.id_for_label }}">{{ form.importo_rata.label_tag }}</label>
            </div>
           
            <div class="form-floating mb-3">
                {% if form.is_bound %}
                {% if form.data_ordine.errors %}
                    {% render_field form.data_ordine class="form-control is-invalid" %}
                    {% for error in form.data_ordine.errors  %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.data_ordine class="form-control is-valid" %}
                {% endif %}
                {% else %}
                    {% render_field form.data_ordine class="form-control" %}
                {% endif %}
                <label class="font-custom" for="{{ form.data_ordine.id_for_label }}">{{ form.data_ordine.label_tag }}</label>
            </div>
    
        </div>    
    
        {% else %}
        <div  class="bottone_viola_info" id ="programma"><p class = 'info_text_button'> Informazioni </p></div>
        
        <div class="grid-form_programma" >
            <div class="form-floating mb-3">
                {% if form.is_bound %}
                {% if form.data_ordine.errors %}
                    {% render_field form.data_ordine class="form-control is-invalid" %}
                    {% for error in form.data_ordine.errors  %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.data_ordine class="form-control is-valid" %}
                {% endif %}
                {% else %}
                    {% render_field form.data_ordine class="form-control" %}
                {% endif %}
                <label class="font-custom" for="{{ form.data_ordine.id_for_label }}">{{ form.data_ordine.label_tag }}</label>
            </div>

            <div class="form-floating mb-3">
                <input type="hidden" name="acconto" value="False">
            </div>

            <div class="form-floating mb-3">
                <input type="hidden" name="rate" value=False>
            </div>

            <div class="form-floating mb-3">
                <input type="hidden" name="importo_rata" value="False">
            </div>
           
            
    
        </div>
        {% endif %}    
    
        
        <div id = 'bottoni_griglia'>
            <button id= 'bottone_prosegui' class="bottone_viola" type="submit"><p id = 'menu_text_button'> Prosegui </p></button>
            
        </div>
        <div id = 'bottoni_griglia'>
            <a href="{% url 'clienti:search_clienti' %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla lista clienti </p></a>
            <a href="{% url 'ordini:scelta_gruppo' id_cliente %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla selezione del programma </p></a>
            <a href="{% url 'ordini:scelta_pagamento' programma.gruppo %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla modalità di pagamento </p></a>
            <a href="{% url 'ordini:scelta_listino' programma.gruppo rat %}" id= 'bottone_prosegui' class="btn bottone_viola"><p id = 'menu_text_button'> Torna alla selezione della durata </p></a>
    
        </div>
    </form>
</div>

{% endblock %}
{% block script %}

  <script>
    $(document).ready(function(){
        $("#id_acconto").blur(calc);
        $("#id_rate").blur(calc);
        
        function calc() {
            
            var tot = '{{programma.importo}}'
            var importo = (((parseFloat(tot)) -parseFloat($('#id_acconto').val())) / parseFloat($("#id_rate").val())).toFixed(2);
            $('#id_importo_rata').val(importo)
           
        };
    })
 
  </script>
  
{% endblock script %}